// lib/swagger.js
const swaggerJSDoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'My API',
      version: '1.0.0',
      description: 'Example API documentation generated by swagger-jsdoc'
    },
    servers: [
      { url: process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3000' }
    ],
    components: {
      securitySchemes: {
        bearerAuth: {            // example JWT bearer auth
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      }
    }
  },
  // adjust globs to where your API route files live
  apis: ['./app/api/**/*.js', './lib/**/*.js']
};

const swaggerSpec = swaggerJSDoc(options);

module.exports = swaggerSpec;
